### ISSUE TITLE
Anchor Error Occurred 

### ISSUE THREAD

**Issue by springrainroni** [anoushk1234/metaplex-anchor-nft#1]
When i try to test the codes it gives me  all data successfully like - 
              mintAuthority,
              mint,
              tokenAccount,
              tokenProgram,
              metadata,
              tokenMetadataProgram,
              payer,
              systemProgram,
              rent,
              masterEdition, 
But when mintNFT function calls then it gives that error.
Error: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.
      at Function.parse (node_modules/@project-serum/anchor/src/error.ts:135:14)
      at translateError (node_modules/@project-serum/anchor/src/error.ts:276:35)
      at Object.rpc [as mintNft] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:35:29)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by anoushk1234** [comment]
<img width="993" alt="Screenshot 2022-04-28 at 3 07 26 PM" src="https://user-images.githubusercontent.com/32778608/165724205-d9eb8777-b839-40e2-911d-726730c9edee.png">
Works for me, i tried it on devnet

**Comment by anoushk1234** [comment]
can you send me your code?

**Comment by springrainroni** [comment]
I updated the dependencies to 
[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
mpl-token-metadata = {version = "1.2.7", features = ["no-entrypoint"]}
so invoke function is not working
Can you please check it

**Comment by springrainroni** [comment]
https://drive.google.com/file/d/1AXZtuNOQQiLL8bo1W1uIg57c54hFKHWa/view?usp=sharing

**Comment by springrainroni** [comment]
I send you the codes
The Problems here
invoke(
            &create_metadata_accounts_v2(
                ctx.accounts.token_metadata_program.key(),
                ctx.accounts.metadata.key(),
                ctx.accounts.mint.key(),
                ctx.accounts.mint_authority.key(),
                ctx.accounts.payer.key(),
                ctx.accounts.payer.key(),
                title,
                symbol,
                uri,
                Some(creator),
                1,
                true,
                false,
                None,
                None
             ),
            account_info.as_slice(),
         )?;
In invoke function

**Comment by anoushk1234** [comment]
> I send you the codes The Problems here invoke( &create_metadata_accounts_v2( ctx.accounts.token_metadata_program.key(), ctx.accounts.metadata.key(), ctx.accounts.mint.key(), ctx.accounts.mint_authority.key(), ctx.accounts.payer.key(), ctx.accounts.payer.key(), title, symbol, uri, Some(creator), 1, true, false, None, None ), account_info.as_slice(), )?; In invoke function

can you put the mint function on the typescript test file in a try catch block and then in the catch just console log the error, you will find the actual error there

**Comment by springrainroni** [comment]
Same error comes.
AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.

**Comment by springrainroni** [comment]
can you solve this issue?anoushk

**Comment by anoushk1234** [comment]
> can you solve this issue?anoushk

hey sorry not sure but you should ask in anchor discord server

**Comment by springrainroni** [comment]
but when i use your code download via github. it shows me same error also that time i did not change the dependancy version.

**Comment by Marchccc** [comment]
@springrainroni 

Hey, did you make it?
i have the same problem

**Comment by springrainroni** [comment]
Did you solve it? 
The solve is that you have to set program token metadata id this one. This is fixed for devnet as much as i know
 const TOKEN_METADATA_PROGRAM_ID = new anchor.web3.PublicKey(
      "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
    );
