### ISSUE TITLE
How to set and verify collection for nfts on solana chain?

### ISSUE THREAD

**Issue by bohdannikita** [anoushk1234/metaplex-anchor-nft#10]
Dear @anoushk1234 
Currently I am learning solana nft collection mint project.
I am following your medium article and got a result for minting one image
But I am not sure how I can develop nft minting contract for nft collection.
Best wishes.

**Comment by anoushk1234** [comment]
<img width="942" alt="Screenshot 2022-10-18 at 2 13 22 PM" src="https://user-images.githubusercontent.com/32778608/196381859-42b63bff-07fc-425f-96e1-78c7ebfa586d.png">

**Comment by bohdannikita** [comment]
Thanks for your reply, @anoushk1234 
Is there any sample code you can recommend for implementing that?
Sorry for disturbing you.

**Comment by anoushk1234** [comment]
> Thanks for your reply, @anoushk1234 Is there any sample code you can recommend for implementing that? Sorry for disturbing you.

There isn't any sample code, if you get stuck just ask in Metaplex discord or solana university discord
