### ISSUE TITLE
program.rpc.mintNft Error

### ISSUE THREAD

**Issue by Marchccc** [anoushk1234/metaplex-anchor-nft#2]
i call the program.rpc.mintNft function,get message:
AnchorError occurred. Error Code: InstructionFallbackNotFound.  Error Number: 101. Error Message: Fallback functions are not supported.

the http response is:
`
{"jsonrpc":"2.0","error":{"code":-32002,"message":"Transaction simulation failed: Error processing Instruction 0: custom program error: 0x65","data":{"accounts":null,"err":{"InstructionError":[0,{"Custom":101}]},"logs":["Program 7YPbUWkByuG4AvRSyTWBWhZtX3wESve6WSaWN6v9NqtA invoke [1]","Program log: Instruction: MintNft","Program log: Initializing Mint Ticket","Program log: CPI Accounts Assigned","Program log: CPI Program Assigned","Program log: CPI Context Assigned","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]","Program log: Instruction: MintTo","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3024 of 1391823 compute units","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success","Program log: Token Minted !!!","Program log: Account Info Assigned","Program log: Creator Assigned","Program 7YPbUWkByuG4AvRSyTWBWhZtX3wESve6WSaWN6v9NqtA invoke [2]","Program log: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.","Program 7YPbUWkByuG4AvRSyTWBWhZtX3wESve6WSaWN6v9NqtA consumed 3835 of 1383632 compute units","Program 7YPbUWkByuG4AvRSyTWBWhZtX3wESve6WSaWN6v9NqtA failed: custom program error: 0x65","Program 7YPbUWkByuG4AvRSyTWBWhZtX3wESve6WSaWN6v9NqtA consumed 20203 of 1400000 compute units","Program 7YPbUWkByuG4AvRSyTWBWhZtX3wESve6WSaWN6v9NqtA failed: custom program error: 0x65"],"unitsConsumed":0}},"id":"babaddd7-87e3-4c3f-a23c-6a604dfb4e9e"}
`

the http payload is :
`
curl 'https://api.devnet.solana.com/' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh,en;q=0.9,zh-CN;q=0.8,ja;q=0.7,de;q=0.6' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3001' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3001/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"method":"sendTransaction","jsonrpc":"2.0","params":["AQ8jk17WkvxpihytOdg2S0XASnncV2y1SdZnZPVjLgpV7+psz+pim3u5Wt/DP4xdNnS/0iKrSeaTJf12wbAgMQEBAAQJx6+9ydsGk4RtVc5BD67YYlUd46TOCoPSbvDkN05X2cRfOJzRd9Q0hIBFLOCZzblvHn6ays8MXU8J1U5v2gv3y3Kcs20X4J0f25frTZl7aJAw53Jz3swkcqMwPczTMYdbc4brqlPee0YFpTJQgLq/vNS6w21xlewR2r8XuQyAp/rgWj/+ntIKa1KJEjMMvBxePlcCrJKrXwDPBo9TdtGDFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYTCsl+KBWgUCeh3QeEESnD+4mDbkx+viPxmmnK5Z+P8Gp9UXGSxcUSGMyUw9SvF/WNruCJuh/UTj29mKAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpY5TeQkS8HbRBvbpRGfRGptBJ4WpHDK8g6UO2iUe51DYBBgoABAgBAwYABQcCeNM5BqcP2yP74Fo//p7SCmtSiRIzDLwcXj5XAqySq18AzwaPU3bRgxQ/AAAAaHR0cHM6Ly9hcndlYXZlLm5ldC95NWU1REpzaXdIMHNfYXlmTXdZay1TbnJadFZaekhMUURTVFo1ZE5SVUhBCQAAAE5GVCBUaXRsZQ==",{"encoding":"base64","preflightCommitment":"processed"}],"id":"babaddd7-87e3-4c3f-a23c-6a604dfb4e9e"}' \
  --compressed
`

**Comment by katopz** [comment]
What's your anchor version?

**Comment by Marchccc** [comment]
> What's your anchor version?

anchor-cli 0.24.2

I've posted the question again on stackoverflow with more details here：
https://stackoverflow.com/questions/72228482/anchorerror-occurred-error-code-instructionfallbacknotfound-error-number-101

**Comment by katopz** [comment]
> > What's your anchor version?
> 
> anchor-cli 0.24.2
> 
> I've posted the question again on stackoverflow with more details here： https://stackoverflow.com/questions/72228482/anchorerror-occurred-error-code-instructionfallbacknotfound-error-number-101

I answered you there.

**Comment by anoushk1234** [comment]
Hey @katopz many thanks for answering this issue, was caught up with work so couldnt respond to these

**Comment by katopz** [comment]
> Hey @katopz many thanks for answering this issue, was caught up with work so couldnt respond to these

no worry, I will make a PR to bring everybody on the same page.

**Comment by anoushk1234** [comment]
merged #4
