### ISSUE TITLE
How to create Collection?

### ISSUE THREAD

**Issue by springrainroni** [anoushk1234/metaplex-anchor-nft#3]
How to create collection? Can you share a sample code?

**Comment by anoushk1234** [comment]
@springrainroni check this https://discord.com/channels/848060988636921856/930305258465411082/951670108340760686

**Comment by springrainroni** [comment]
can you give me any sample code please?

**Comment by gvko** [comment]
@anoushk1234 , this Discord link leads to no channel or group. 🤔

**Comment by anoushk1234** [comment]
@gvko its the metaplex discord server
