### ISSUE TITLE
Custom Program ID in the mint test

### ISSUE THREAD

**Issue by gvko** [anoushk1234/metaplex-anchor-nft#5]
Hey guys! I found your repo from your [Medium tutorial](https://betterprogramming.pub/how-to-mint-nfts-on-solana-using-rust-and-metaplex-f66bac717cb8)! Great tutorial, very helpful!

I wanted to ask about [this specific line](https://github.com/anoushk1234/metaplex-anchor-nft/blob/27b17cb40670dc99bc78a3e775e5eb04184995b4/tests/metaplex-anchor-nft.ts#L18).

When I substitute the ID with my custom program ID (the one I got once I did `anchor build & anchor deploy`) - it doesn't work anymore. I still have to use the one provided in your code.

Do you know why is that happening? Both IDs are of an executable `Program`. The only difference I found is that the one you provide the ID of in your code also has `Public name: Metaplex Token Metadata`, when observed on the Solana block explorer.

[SOL block explorer for Program provided in your code](https://solscan.io/account/metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s?cluster=devnet)
[SOL block explorer for Program deployed by me](https://solscan.io/account/BaRowwkbSzfwxpbr64yzq8Hxmh3o8zS4PXb6KFZukkL2?cluster=devnet)

**Comment by anoushk1234** [comment]
@gvko that id is not supposed to be used in place of your program id thats the metaplex program which your invoking

**Comment by gvko** [comment]
@anoushk1234 What does that mean exactly?
I guess I'm having lack of understanding, cuz I'm confused.
The program that I deploy is the program that mints my tokens, right? Something like a smart contract on ETH.
What does the metaplex program has to do in this whole process?

**Comment by gvko** [comment]
I'm asking this because I'd like to understand how the process works under the hood, but not be just a minting user. 
Why do we need the metaplex program? In the Metaplex project, is the Candy Machine just a name for a smart contract that mints the tokens?
How is it used under the hood?

**Comment by anoushk1234** [comment]
> I'm asking this because I'd like to understand how the process works under the hood, but not be just a minting user. Why do we need the metaplex program? In the Metaplex project, is the Candy Machine just a name for a smart contract that mints the tokens? How is it used under the hood?

checkout https://docs.metaplex.com it explains what metaplex and candymachine is

**Comment by anoushk1234** [comment]
> @anoushk1234 What does that mean exactly? I guess I'm having lack of understanding, cuz I'm confused. The program that I deploy is the program that mints my tokens, right? Something like a smart contract on ETH. What does the metaplex program has to do in this whole process?

your program is minting the token but metaplex is used to convert it to an nft standard with metadata thats recognized universally

**Comment by gvko** [comment]
@anoushk1234 , maybe a few last questions:
1. this Metaplex program was deployed by the Metaplex team on `devnet`, right?
2. is there such a program on `mainnet` as well?
3. if I create/deploy my own Candy Machine - is that going to be the program minting the token or is it going to be the program creating the associated accounts (like in your tutorial)? 

Thanks a lot for your help! 🙏

**Comment by anoushk1234** [comment]
> @anoushk1234 , maybe a few last questions:
> 
>     1. this Metaplex program was deployed by the Metaplex team on `devnet`, right?
> 
>     2. is there such a program on `mainnet` as well?
> 
>     3. if I create/deploy my own Candy Machine - is that going to be the program minting the token or is it going to be the program creating the associated accounts (like in your tutorial)?
> 
> 
> Thanks a lot for your help! 🙏

yes deployed on devnet, yes its there on mainnet, it will be minting the token if u use candymachine

**Comment by gvko** [comment]
> > @anoushk1234 , maybe a few last questions:
> > ```
> > 1. this Metaplex program was deployed by the Metaplex team on `devnet`, right?
> > 
> > 2. is there such a program on `mainnet` as well?
> > 
> > 3. if I create/deploy my own Candy Machine - is that going to be the program minting the token or is it going to be the program creating the associated accounts (like in your tutorial)?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks a lot for your help! 🙏
> 
> yes deployed on devnet, yes its there on mainnet, it will be minting the token if u use candymachine

What is the address of it on `mainnet`? Or where/how can I find it?

**Comment by anoushk1234** [comment]
> > > @anoushk1234 , maybe a few last questions:
> 
> > > ```
> 
> > > 1. this Metaplex program was deployed by the Metaplex team on `devnet`, right?
> 
> > > 
> 
> > > 2. is there such a program on `mainnet` as well?
> 
> > > 
> 
> > > 3. if I create/deploy my own Candy Machine - is that going to be the program minting the token or is it going to be the program creating the associated accounts (like in your tutorial)?
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > Thanks a lot for your help! 🙏
> 
> > 
> 
> > yes deployed on devnet, yes its there on mainnet, it will be minting the token if u use candymachine
> 
> 
> 
> What is the address of it on `mainnet`? Or where/how can I find it?

Same as the devnet address
